config/routes.rb
Rails.application.routes.draw do
  get 'listings/new'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create, :edit, :update] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
      # resources :listings
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "users#index"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "/profile" => "users#profile"

  resources :listings do 
    resources :reservations
  end 

  get "/search" => "listings#search"
  post "/listings/:id/verify" => "listings#verify", as: 'verify'

  resources :reservations, only: [:show] do 
    get "braintree/new" => "braintree#new"
    post "braintree/checkout" => "braintree#checkout"
  end 

  get "/reservations" => "reservations#all"
end

app/models/listing.rb
class Listing < ApplicationRecord
	belongs_to :user
	has_many :reservations
	mount_uploaders :photos, PhotoUploader
	scope :category, -> (category) { category.blank? ? all : where("category ilike ?",  "%#{category}%")}
	scope :guest, -> (guest) { guest.blank? ? all : where(number_of_guest: guest)}
	scope :general, -> (general) { 
		if general.blank? 
			all
		else 
			# keyword = general.split
			# query = ["title ilike ? or location ilike ?"] * keyword.count
			# joined = query.join(' or ')
			# a = (keyword.map { |i| ["%#{i}%"]*query.count }).flatten

			# where([joined] +  a)

			relation = Listing.where(id: 0)
			general.split.each do |j|
				relation = relation.or(Listing.where("title ilike ? or location ilike ?", "%#{j}%", "%#{j}%"))
			end 
			relation
		end 	
	}
	scope :type, -> (type) { type.blank? ? all : where(type_of_room: type)}

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :listing_allowed?, only: [:edit, :update, :destroy]

	def index 
		@listing = [] 
		@host = [] 
		@listings = Listing.where(user_id: current_user.id)
		@merge = @listings.order("id ASC").paginate(:page => params[:page], :per_page => 10)
	end 

  def new
  	@listing = Listing.new 
  end
  
  def show
  	@listing = Listing.find(params[:id])
    # byebug 
  end 

  def edit 
  	# byebug 
    listing_allowed?(@listing = Listing.find(params[:id]), params)
  end 

  def update 
    @a = Listing.find(params[:id])
  	@listing = @a.update(listing_params)
  	location = @a.location
  	flash[:update] = "Your listing at #{location} has been updated"
  	redirect_to listing_path(params[:id])
  end 

  def create 
  	@listing = current_user.listings.new(listing_params)

  	if @listing.save 
  		flash[:save] = "your listing has been save"
  		redirect_to listing_path(@listing.id)
  	else 
  		flash[:save] = "your listing has not been saved"
  		redirect_to new_listings_path 
  	end 
  end 

  def search
    hash = Hash[search_params.keys.zip(search_params.values)]
    @listing = Listing
    # params[:listing] = {category: 'aaa', guest: 'bbb', general: 'ccc'}
    hash.each do |key, value|
      @listing = @listing.send(key, value)
      # Listing.send(:category, 'aaa')
      # Lising.category('aaa')

      # Listing.category('aaa').send(:guest, 'bbb')
      # Listing.category('aaa').guest('bbb')
      # byebug 
    end

  	  @search_result = [search_params]
      @search_result = @search_result.reject { |i| i.empty? }
  	@merge = @listing.paginate(:page => params[:page], :per_page => 10)

  end 

  def destroy 
    Listing.delete(params[:id])
    flash[:destroy] = "Your listing has been deleted"
    redirect_to listings_path
  end 

  def verify 
    @verification = Listing.find(params[:id])
    if allowed? == true 
      if @verification.verify == true
        @verify = @verification.update(verify: false)
        flash[:notice] = "The post has been unverified"
      else 
        @verify = @verification.update(verify: true)
        flash[:notice] = "The post has been verified"
      end 
    else
      flash[:notice] = "You have no authority to verify the post"
    end 
    redirect_to root_path
  end 


  private
  def listing_params
  	params.require(:listing).permit(:title, :number_of_guest, :price, :category, 
      :location, :type_of_room, photos: [])
  end

  def search_params 
      params.require(:search).permit(:general, :category, :guest, :type)
  end 
end

app/helpers/listing_helper.rb
module ListingHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
	<div class="title-field">
	  <%= form.label :title %> :
	  <%= form.text_field :title %>
	</div>
	<br> 

	<div class="location-field">
	  <%= form.label :location %> :
	  <%= form.text_field :location %>
	</div>
	</br>

	<div class="guest-field">
	  <%= form.label :number_of_guest %> : 
	  <%= form.number_field :number_of_guest %>
	</div>
	</br>

	<div class="room-field">
		<%= form.label :type_of_room %> : 
		<%= form.select "type_of_room", options_for_select([["Select Room", ""],["Private Room", "Private Room"],["Entire Place", "Entire Place"],["Shared Room", "Shared Room"]]) , {}, {:class => "form-control"} %>
	</div>

	</br>

	<div class="category-field">
		<%= form.label :category %> : 
		<%= form.select "category", options_for_select([["Select Category", ""], ["Smoker", "Smoker"], ["Non-Smoker", "Non-Smoker"], ["Pet", "Pet"]]) , {}, {:class => "form-control"}%>
	</div>
	</br>

	<div class="price-field">
	  <%= form.label :price_per_night %> : 
	  <%= form.number_field :price %>
	</div>

app/views/listings/edit.html.erb
<br> 
<div class='edit-form'>
	<div class='edit-context'>
	<h1 style="color: white;"> Edit your form here </h1>
		<br> 
		<%= form_for @listing do |form| %>
		  <%= render partial: '/listings/form', object: form %>
		  <br>
		  <%= form.file_field :photos, multiple: true, class: "form-control" %>
		  <%= form.submit class: "btn btn-primary" %>
		  <br> 
		<% end %>
	</div>
	<br> 
</div>

app/views/listings/index.html.erb
<br> 
<% @merge.order("id ASC").each do |i| %> 
	<div class="card card-cascade">

		    <!--Card image-->
		  <div id="myCarousel" class="carousel slide" data-ride="carousel">
		  	       <div id="carouselExampleControls-<%= i.id %>" class="carousel slide" data-ride="carousel">
		  	       		  <div class="carousel-inner" role="listbox">

		  	       		  	<div class="carousel-item active">
		  		       		  	<% if i.photos[0] == nil %>
		  		       		  		<%= image_tag "https://www.landmarklondon.co.uk/uploads/files/Executive-Room.jpg", class: "picture" %>
		  		       		  	</div>
		  		       		  	<div class="carousel-item">
		  		       		  		<%= image_tag "https://thumbs.dreamstime.com/z/five-star-hotel-room-2688844.jpg", class: "picture" %>
		  	       		  		</div>
		  		       		  	<% else %>
		  		       		  	  <%= image_tag "#{i.photos[0].url}", class: "d-block img-fluid"%>
		  		       		  	</div>
		  			       		  <% i.photos[1..-1].each do |j| %>
		  			       		    <div class="carousel-item">
		  			       		      <%= image_tag j.url, class: "d-block img-fluid"%>
		  			       		    </div>
		  			       			<% end %>
		  		       			<% end %>	
		  	       		  </div>
		  		       		  <a class="carousel-control-prev" href="#carouselExampleControls-<%= i.id %>" role="button" data-slide="prev">
		  		       		    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
		  		       		    <span class="sr-only">Previous</span>
		  		       		  </a>
		  		       		  <a class="carousel-control-next" href="#carouselExampleControls-<%= i.id %>" role="button" data-slide="next">
		  		       		    <span class="carousel-control-next-icon" aria-hidden="true"></span>
		  		       		    <span class="sr-only">Next</span>
		  		       		  </a>
		  	       </div>
		  		</div>
		    <!--/.Card image-->

		    <!--Card content-->
		    <div class="card-body">
		        <!--Title-->
		        <h4 class="card-title" style="font-weight: bold;"><%= i.title %> </h4>
		        <!--Text-->
		        <p class="card-text">Location: <%= i.location %></p>
		        <p class="card-text">Number of guest: <%= i.number_of_guest %></p>
		        <p class="card-text">Price per night: $<%= i.price %></p>
		        <p class="card-text">Type of room: <%= i.type_of_room %></p>
		        <p class="card-text">Category: <%= i.category %></p>
		        <%= link_to "edit", edit_listing_path(i.id) %>
		        <%= link_to "delete", listing_path(i.id), method: :delete %>
		    </div>
		    <!--/.Card content-->
		    <h10 class="hosted">Hosted By:<%= i.user.name %></h10><br>
		    <% if i.verify == true %>
		    	<%= link_to "Verified by admin", verify_path(i.id), method: :post %> 
		    <% else %>
		    	<%= link_to "Not verified by admin", verify_path(i.id), method: :post %> 
		    <% end %> 
		</div>
		<br> 
<% end %> 

<%= will_paginate @merge %>

app/views/listings/new.html.erb
<div class='lists' > 
	<div class='greetings'>
		<h1>Hi, there! Let's get started listing your place </h1>
	</div>

	<div class='create_listings'>
		<%= form_for @listing do |form| %>
			<%= render partial: '/listings/form', object: form %>
			</br>
			<%= form.file_field :photos, multiple: true, class: "form-control" %>
			<div class="listing-field">
			  <%= form.submit %>
			</div>
			</br>
		<% end %>
	</div>
</div>

app/views/listings/search.html.erb
<h1> Seach Result </h1>
<% if @search_result != nil %>
	<% @search_result.each do |i| %>
		<%= i %><br>
	<% end %>
<% end %>

<% if @merge == nil %>
<p>No such listings exist</p>
<% else %>
	<% @merge.each do |i| %>
		<!--Card Narrower-->
		<div class="card card-cascade">

		    <!--Card image-->
		   <div id="myCarousel" class="carousel slide" data-ride="carousel">
		   	       <div id="carouselExampleControls-<%= i.id %>" class="carousel slide" data-ride="carousel">
		   	       		  <div class="carousel-inner" role="listbox">

		   	       		  	<div class="carousel-item active">
		   		       		  	<% if i.photos[0] == nil %>
		   		       		  		<%= image_tag "https://www.landmarklondon.co.uk/uploads/files/Executive-Room.jpg", class: "picture" %>
		   		       		  	</div>
		   		       		  	<div class="carousel-item">
		   		       		  		<%= image_tag "https://thumbs.dreamstime.com/z/five-star-hotel-room-2688844.jpg", class: "picture" %>
		   	       		  		</div>
		   		       		  	<% else %>
		   		       		  	  <%= image_tag "#{i.photos[0].url}", class: "d-block img-fluid"%>
		   		       		  	</div>
		   			       		  <% i.photos[1..-1].each do |j| %>
		   			       		    <div class="carousel-item">
		   			       		      <%= image_tag j.url, class: "d-block img-fluid"%>
		   			       		    </div>
		   			       			<% end %>
		   		       			<% end %>	
		   	       		  </div>
		   		       		  <a class="carousel-control-prev" href="#carouselExampleControls-<%= i.id %>" role="button" data-slide="prev">
		   		       		    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
		   		       		    <span class="sr-only">Previous</span>
		   		       		  </a>
		   		       		  <a class="carousel-control-next" href="#carouselExampleControls-<%= i.id %>" role="button" data-slide="next">
		   		       		    <span class="carousel-control-next-icon" aria-hidden="true"></span>
		   		       		    <span class="sr-only">Next</span>
		   		       		  </a>
		   	       </div>
		   		</div>
		    <!--/.Card image-->

		    <!--Card content-->
		    <div class="card-body">
		        <!--Title-->
		        <h4 class="card-title" style="font-weight: bold;"><%= i.title %> </h4>
		        <!--Text-->
		        <p class="card-text">Location: <%= i.location %></p>
		        <p class="card-text">Number of guest: <%= i.number_of_guest %></p>
		        <p class="card-text">Price per night: $<%= i.price %></p>
		        <p class="card-text">Type of room: <%= i.type_of_room %></p>
		        <p class="card-text">Category: <%= i.category %></p>

		        <%= button_to "Book Now" , new_listing_reservation_path(i.id), method: :get, class: "btn btn-primary" %>
		    </div>
		    <!--/.Card content-->
		    <h10 class="hosted">Hosted By:<%= i.user.name %></h10><br>
		    <% if i.verify == true %>
		    	<%= link_to "Verified by admin", verify_path(i.id), method: :post %> 
		    <% else %>
		    	<%= link_to "Not verified by admin", verify_path(i.id), method: :post %> 
		    <% end %> 
		</div>
		<br> 
		<!--/.Card Narrower-->
	<% end %>
<% end %>
<%= will_paginate @merge %>

app/views/listings/show.html.erb
<br>
<% if @errors %> 
  <%= @errors %>
<% end %>
<div class="card card-cascade">

    <!--Card image-->
   <div id="myCarousel" class="carousel slide" data-ride="carousel">
           <div id="carouselExampleControls-<%= @listing.id %>" class="carousel slide" data-ride="carousel">
                  <div class="carousel-inner" role="listbox">

                    <div class="carousel-item active">
                        <% if @listing.photos == [] %>
                            <%= image_tag "https://www.landmarklondon.co.uk/uploads/files/Executive-Room.jpg", class: "picture" %>
                        </div>
                        <div class="carousel-item">
                            <%= image_tag "https://thumbs.dreamstime.com/z/five-star-hotel-room-2688844.jpg", class: "picture" %>
                        </div>
                        <% else %>
                          <%= image_tag "#{@listing.photos[0].url}", class: "d-block img-fluid"%>
                        </div>
                          <% @listing.photos[1..-1].each do |j| %>
                            <div class="carousel-item">
                              <%= image_tag j.url, class: "d-block img-fluid"%>
                            </div>
                            <% end %>
                        <% end %>   
                  </div>
                      <a class="carousel-control-prev" href="#carouselExampleControls-<%= @listing.id %>" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                      </a>
                      <a class="carousel-control-next" href="#carouselExampleControls-<%= @listing.id %>" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                      </a>
           </div>
        </div>
    <!--/.Card image-->

    <!--Card content-->
    <div class="card-body">
        <!--Title-->
        <h4 class="card-title" style="font-weight: bold;"><%= @listing.title %> </h4>
        <!--Text-->
        <p class="card-text">Location: <%= @listing.location %></p>
        <p class="card-text">Number of guest: <%= @listing.number_of_guest %></p>
        <p class="card-text">Price per night: $<%= @listing.price %></p>
        <p class="card-text">Type of room: <%= @listing.type_of_room %></p>
        <p class="card-text">Category: <%= @listing.category %></p>
        
        <% if @listing.user_id == current_user.id %>
          <%= link_to "edit", edit_listing_path %>
          <%= link_to "home", root_path %>
        <% end %>
    </div>
    <!--/.Card content-->
    <h10 class="hosted">Hosted By:<%= User.find(@listing.user_id).name  %></h10><br>
    <% if @listing.verify == true %>
        <%= link_to "Verified by admin", verify_path(@listing.id), method: :post %> 
    <% else %>
        <%= link_to "Not verified by admin", verify_path(@listing.id), method: :post %> 
    <% end %> 
</div>
<br>