config/routes.rb
Rails.application.routes.draw do
  get 'listings/new'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create, :edit, :update] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
      # resources :listings
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "users#index"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "/profile" => "users#profile"

  resources :listings do 
    resources :reservations
  end 

  get "/search" => "listings#search"
  post "/listings/:id/verify" => "listings#verify", as: 'verify'

  resources :reservations, only: [:show] do 
    get "braintree/new" => "braintree#new"
    post "braintree/checkout" => "braintree#checkout"
  end 

  get "/reservations" => "reservations#all"
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  has_many :authentications, dependent: :destroy
  has_many :listings 
  has_many :reservations
  mount_uploader :avatar, AvatarUploader

     def self.create_with_auth_and_hash(authentication, auth_hash)
       user = self.create!(
         name: auth_hash["extra"]["raw_info"]["name"],
         email: auth_hash["extra"]["raw_info"]["email"],
         password: SecureRandom.hex(10) 
       )
       user.authentications << authentication
       return user
     end

     # grab fb_token to access Facebook for user data
     def fb_token
       x = self.authentications.find_by(provider: 'facebook')
       return x.token unless x.nil?
     end
end 

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
	before_action :require_login,  only: [:index, :edit, :update]
	def create 
		@user = user_from_params
		# byebug 
	    if @user.save
	      sign_in @user
	      redirect_back_or url_after_create
	    else
	      render template: "users/new"
		end
	end 
	def index 

		@email = current_user.email 
		@listings = Listing.where.not(user_id: current_user.id)

		# @merge = @not_my_listing.zip(@user)
		@merge = @listings.paginate(:page => params[:page], :per_page => 10)
		@verified = "Verify by admin"
		# byebug 
	end 

	def edit 
		user_allowed?(@users = User.find(params[:id]) , params)
        # byebug      
	end 

	def update 
		@users = User.update(user_params)
		flash[:update] = "User #{params[:name]} has been updated"
		redirect_to root_path 
	end 

	def profile 
		@user = User.find(current_user.id).email 
	end 

	private 
	 def user_from_params
	    email = user_params.delete(:email)
	    password = user_params.delete(:password)
	    name = user_params.delete(:name)
	    avatar = user_params.delete(:avatar)
	    # byebug 
	    Clearance.configuration.user_model.new(user_params).tap do |user|
	      user.email = email
	      user.password = password
	      user.name = name 
	      user.avatar = avatar 
	    end

	end

	def user_params 
		params.require(:user).permit(:name, :email, :password, :avatar)
	end 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %> :
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="name-field">
  <%= form.label :name %> :
  <%= form.text_field :name, type: 'name' %>
</div>

<div class="password-field">
  <%= form.label :password %> : 
  <%= form.password_field :password %>
</div>

app/views/users/edit.html.erb
	<%= form_for @users do |i|%>
		name: <%= i.text_field :name %><br>
		email: <%= i.text_field :email %><br>
		<%= i.file_field :avatar, class: "form-control" %><br>
		<%= i.submit %>
	<% end %>

app/views/users/index.html.erb
<p> Hello user <%= @email %></p>
<%= @update %>

<% @merge.order("id ASC").each do |i| %> 
	<div class="card card-cascade">
		<div id="myCarousel" class="carousel slide" data-ride="carousel">
	       <div id="carouselExampleControls-<%= i.id %>" class="carousel slide" data-ride="carousel">
	       		  <div class="carousel-inner" role="listbox">

	       		  	<div class="carousel-item active">
		       		  	<% if i.photos[0] == nil %>
		       		  		<%= image_tag "https://www.landmarklondon.co.uk/uploads/files/Executive-Room.jpg", class: "picture" %>
		       		  	</div>
		       		  	<div class="carousel-item">
		       		  		<%= image_tag "https://thumbs.dreamstime.com/z/five-star-hotel-room-2688844.jpg", class: "picture" %>
	       		  		</div>
		       		  	<% else %>
		       		  	  <%= image_tag "#{i.photos[0].url}", class: "d-block img-fluid"%>
		       		  	</div>
			       		  <% i.photos[1..-1].each do |j| %>
			       		    <div class="carousel-item">
			       		      <%= image_tag j.url, class: "d-block img-fluid"%>
			       		    </div>
			       			<% end %>
		       			<% end %>	
	       		  </div>
		       		  <a class="carousel-control-prev" href="#carouselExampleControls-<%= i.id %>" role="button" data-slide="prev">
		       		    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
		       		    <span class="sr-only">Previous</span>
		       		  </a>
		       		  <a class="carousel-control-next" href="#carouselExampleControls-<%= i.id %>" role="button" data-slide="next">
		       		    <span class="carousel-control-next-icon" aria-hidden="true"></span>
		       		    <span class="sr-only">Next</span>
		       		  </a>
	       </div>
		</div>
	 

	    <!--Card content-->
	    <div class="card-body">
	        <!--Title-->
	        <h4 class="card-title" style="font-weight: bold;"><%= i.title %> </h4>
	        <!--Text-->
	        <p class="card-text">Location: <%= i.location %></p>
	        <p class="card-text">Number of guest: <%= i.number_of_guest %></p>
	        <p class="card-text">Price per night: $<%= i.price %></p>
	        <p class="card-text">Type of room: <%= i.type_of_room %></p>
	        <p class="card-text">Category: <%= i.category %></p>
	        <%= button_to "Book Now" , new_listing_reservation_path(i.id), method: :get, class: "btn btn-primary" %>
	    </div>
	    <!--/.Card content-->
	    <h10 class="hosted">Hosted By: <%= i.user.name %></h10>
	    <% if i.verify == true %>
	    	<%= link_to "Verified by admin", verify_path(i.id), method: :post %> 
	    <% else %>
	    	<%= link_to "Not verified by admin", verify_path(i.id), method: :post %> 
	    <% end %> 
	</div>
	<br> 
	<!--/.Card Narrower-->
<% end %>
<%= will_paginate @merge %>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <div class='container'>
    <div class="title">
      <h2><%= t(".title") %></h2>
    </div>

    <%= form_for @user do |form| %>
      <%= render partial: '/users/form', object: form %>
      <br>
      <%= form.file_field :avatar, class: "form-control" %>
      <br> 
      <div class="submit-field">
        <%= form.submit %>
      </div>

      <div class="other-links">
        <%= link_to t(".sign_in"), sign_in_path %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/profile.html.erb
<p> Hello user <%= @user %> </p>

<%= link_to "Create Listing", new_listing_path %> 
<br>
<%= link_to "Show all my listings" , listings_path %>
<br> 
<%= link_to "Show all my reservations" , reservations_path %>
<br>

<%= link_to "Edit profile", edit_user_path(current_user.id) %>