config/routes.rb
Rails.application.routes.draw do
  get 'listings/new'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create, :edit, :update] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
      # resources :listings
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "users#index"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "/profile" => "users#profile"

  resources :listings do 
    resources :reservations
  end 

  get "/search" => "listings#search"
  post "/listings/:id/verify" => "listings#verify", as: 'verify'

  resources :reservations, only: [:show] do 
    get "braintree/new" => "braintree#new"
    post "braintree/checkout" => "braintree#checkout"
  end 

  get "/reservations" => "reservations#all"
end

app/models/reservation.rb
class Reservation < ApplicationRecord
	belongs_to :user 
	belongs_to :listing
	validate :overlapping_dates, on: :create

	def overlapping_dates 
		# byebug
		listing.reservations.each do |old_booking|
			if overlap?(self,old_booking)
				return errors.add(:overlapping_dates,
				 "The reservation has already been booked")
			end 
		end 
	end 

	# def date_not_available

	def overlap?(x,y)	
		# byebug
		(Time.parse(x.check_in) - Time.parse(y.check_out)) * (Time.parse(y.check_in) - Time.parse(x.check_out)) > 0 ;
	end 
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
	before_action  :reservation_allowed?, only: [ :destroy]
	def new 
		@listing = Listing.find(params[:listing_id])
		@reservation = @listing.reservations.new
		# byebug 
	end

	def create 
		@reservation = Reservation.new(reservation_params)
		@reservation.user_id = current_user.id
		@reservation.listing_id = params[:listing_id]
		@reservation.price = (DateTime.parse(@reservation.check_out) - DateTime.parse(
			@reservation.check_in)).to_i * @reservation.listing.price 

		if @reservation.save 
			flash[:notice] = "Your reservation has been booked"
			redirect_to listing_reservation_path(@reservation.listing, @reservation)
		else 
			# byebug 
			flash[:error] = @reservation.errors.full_messages
			redirect_to root_path 
		end 

	end  

	def show 
		@listing = Listing.find(params[:listing_id])
		@reservation = Reservation.find(params[:id])
		@total_price = (DateTime.parse(@reservation.check_out) - DateTime.parse(
			@reservation.check_in)).to_i * @listing.price 
		# byebug 
	end 

	def all
		@reservations = current_user.reservations 
		@total_price = []
		@listing = [] 
		@reservations.each do |i|
			@listing << i.listing 
		end 
		@merge = @reservations.zip(@listing, @total_price)
	end 

	def destroy 
		reservation = Reservation.delete(params[:id])
		flash[:notice] = "Your reservation has been canceled"
		redirect_to reservations_path 
	end 

	private 
	def reservation_params 
		params.require(:reservation).permit(:check_in, :check_out, :listing_id)
	end 
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/all.html.erb
<br>
<% @merge.each do |i| %> 
	<div class="card card-cascade">
		<div id="myCarousel" class="carousel slide" data-ride="carousel">
	       <div id="carouselExampleControls-<%= i[1].id %>" class="carousel slide" data-ride="carousel">
	       		  <div class="carousel-inner" role="listbox">

	       		  	<div class="carousel-item active">
		       		  	<% if i[1].photos[0] == nil %>
		       		  		<%= image_tag "https://www.landmarklondon.co.uk/uploads/files/Executive-Room.jpg", class: "picture" %>
		       		  	</div>
		       		  	<div class="carousel-item">
		       		  		<%= image_tag "https://thumbs.dreamstime.com/z/five-star-hotel-room-2688844.jpg", class: "picture" %>
	       		  		</div>
		       		  	<% else %>
		       		  	  <%= image_tag "#{i[1].photos[0].url}", class: "d-block img-fluid"%>
		       		  	</div>
			       		  <% i[1].photos[1..-1].each do |j| %>
			       		    <div class="carousel-item">
			       		      <%= image_tag j.url, class: "d-block img-fluid"%>
			       		    </div>
			       			<% end %>
		       			<% end %>	
	       		  </div>
		       		  <a class="carousel-control-prev" href="#carouselExampleControls-<%= i[1].id %>" role="button" data-slide="prev">
		       		    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
		       		    <span class="sr-only">Previous</span>
		       		  </a>
		       		  <a class="carousel-control-next" href="#carouselExampleControls-<%= i[1].id %>" role="button" data-slide="next">
		       		    <span class="carousel-control-next-icon" aria-hidden="true"></span>
		       		    <span class="sr-only">Next</span>
		       		  </a>
	       </div>
		</div>
	 

	    <!--Card content-->
	    <div class="card-body">
	        <!--Title-->
	        <h4 class="card-title" style="font-weight: bold;"><%= i[1].title %> </h4>
	        <!--Text-->
	        <p class="card-text">Location: <%= i[1].location %></p>
	        <p class="card-text">Number of guest: <%= i[1].number_of_guest %></p>
	        <p class="card-text">Price per night: $<%= i[1].price %></p>
	        <p class="card-text">Type of room: <%= i[1].type_of_room %></p>
	        <p class="card-text">Category: <%= i[1].category %></p>
			<hr>
			<p class="card-text" style='font-weight: bold;'>Check-in date: <%= i[0].check_in %></p>
			<p class="card-text" style='font-weight: bold;'>Check-out date: <%= i[0].check_out %></p>  
			<p class="card-text" style='font-weight: bold;'>Total payable amount: $<%= i[0].price %></p>  
			<hr> 

			<% if i[0].paid_statusm == true %> 
				<p style='font-weight: bold;'> Paid </p>
			<% else %>
				<%= button_to "Pay now", reservation_braintree_new_path(i[0].id) , method: :get , class: "btn btn-primary"%>
				<br> 
				<%= button_to "Cancel Booking", listing_reservation_path(i[1].id, i[0].id), method: :delete , class: "btn btn-danger"%>
			<% end %>
	    </div>
	    <!--/.Card content-->
	    <h10 class="hosted">Hosted By: <%= i[0].user.name %></h10>
	    <br>
	    <% if i[1].verify == true %>
	    	<%= link_to "Verified by admin", verify_path(i[1].id), method: :post %> 
	    <% else %>
	    	<%= link_to "Not verified by admin", verify_path(i[1].id), method: :post %> 
	    <% end %> 
	</div>
	<br> 
	<!--/.Card Narrower-->
<% end %>

app/views/reservations/new.html.erb
<br>
<div class="card card-cascade">

	    <!--Card image-->
	  <div id="myCarousel" class="carousel slide" data-ride="carousel">
	  	       <div id="carouselExampleControls-<%= @listing.id %>" class="carousel slide" data-ride="carousel">
	  	       		  <div class="carousel-inner" role="listbox">

	  	       		  	<div class="carousel-item active">
	  		       		  	<% if @listing.photos[0] == nil %>
	  		       		  		<%= image_tag "https://www.landmarklondon.co.uk/uploads/files/Executive-Room.jpg", class: "picture" %>
	  		       		  	</div>
	  		       		  	<div class="carousel-item">
	  		       		  		<%= image_tag "https://thumbs.dreamstime.com/z/five-star-hotel-room-2688844.jpg", class: "picture" %>
	  	       		  		</div>
	  		       		  	<% else %>
	  		       		  	  <%= image_tag "#{@listing.photos[0].url}", class: "d-block img-fluid"%>
	  		       		  	</div>
	  			       		  <% @listing.photos[1..-1].each do |j| %>
	  			       		    <div class="carousel-item">
	  			       		      <%= image_tag j.url, class: "d-block img-fluid"%>
	  			       		    </div>
	  			       			<% end %>
	  		       			<% end %>	
	  	       		  </div>
	  		       		  <a class="carousel-control-prev" href="#carouselExampleControls-<%= @listing.id %>" role="button" data-slide="prev">
	  		       		    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
	  		       		    <span class="sr-only">Previous</span>
	  		       		  </a>
	  		       		  <a class="carousel-control-next" href="#carouselExampleControls-<%= @listing.id %>" role="button" data-slide="next">
	  		       		    <span class="carousel-control-next-icon" aria-hidden="true"></span>
	  		       		    <span class="sr-only">Next</span>
	  		       		  </a>
	  	       </div>
	  		</div>
	    <!--/.Card image-->

	    <!--Card content-->
	    <div class="card-body">
	        <!--Title-->
	        <h4 class="card-title" style="font-weight: bold;"><%= @listing.title %> </h4>
	        <!--Text-->
	        <p class="card-text">Location: <%= @listing.location %></p>
	        <p class="card-text">Number of guest: <%= @listing.number_of_guest %></p>
	        <p class="card-text">Price per night: $<%= @listing.price %></p>
	        <p class="card-text">Type of room: <%= @listing.type_of_room %></p>
	        <p class="card-text">Category: <%= @listing.category %></p>
				<%= form_for [@listing, @reservation] do |f| %>
			        <p style='font-style: italic; font-weight: bold;'> Check in date </p>
					<input type='hidden' value='@listing.id' name='listing_id'>
			        <%=  f.date_field :check_in, class: 'checkin', min: Date.today %>
			        <p style='font-style: italic; font-weight: bold;'> Check out date </p>
			        <%=  f.date_field :check_out, class: 'checkout' %>
			        <br> 
			        <%=  f.submit class: "btn btn-primary" %>
				<% end %>
	    </div>

	    <p style='font-size: 80%; text-align: center;'> Check in and check out times must be before 1pm and 10am respectively </p>
	    <!--/.Card content-->
	    <h10 class="hosted" style='font-size: 80%;'>Hosted By:<%= @listing.user.name %></h10><br>
	    <% if @listing.verify == true %>
	    	<%= link_to "Verified by admin", verify_path(@listing.id), method: :post %> 
	    <% else %>
	    	<%= link_to "Not verified by admin", verify_path(@listing.id), method: :post %> 
	    <% end %> 
	</div>
	<br> 

app/views/reservations/show.html.erb
<div class="card card-cascade">

    <!--Card image-->
   <div id="myCarousel" class="carousel slide" data-ride="carousel">
           <div id="carouselExampleControls-<%= @listing.id %>" class="carousel slide" data-ride="carousel">
                  <div class="carousel-inner" role="listbox">

                    <div class="carousel-item active">
                        <% if @listing.photos == [] %>
                            <%= image_tag "https://www.landmarklondon.co.uk/uploads/files/Executive-Room.jpg", class: "picture" %>
                        </div>
                        <div class="carousel-item">
                            <%= image_tag "https://thumbs.dreamstime.com/z/five-star-hotel-room-2688844.jpg", class: "picture" %>
                        </div>
                        <% else %>
                          <%= image_tag "#{@listing.photos[0].url}", class: "d-block img-fluid"%>
                        </div>
                          <% @listing.photos[1..-1].each do |j| %>
                            <div class="carousel-item">
                              <%= image_tag j.url, class: "d-block img-fluid"%>
                            </div>
                            <% end %>
                        <% end %>   
                  </div>
                      <a class="carousel-control-prev" href="#carouselExampleControls-<%= @listing.id %>" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                      </a>
                      <a class="carousel-control-next" href="#carouselExampleControls-<%= @listing.id %>" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                      </a>
           </div>
        </div>
    <!--/.Card image-->

    <!--Card content-->
    <div class="card-body">
        <!--Title-->
        <h4 class="card-title" style="font-weight: bold;"><%= @listing.title %> </h4>
        <!--Text-->
        <p class="card-text">Location: <%= @listing.location %></p>
        <p class="card-text">Number of guest: <%= @listing.number_of_guest %></p>
        <p class="card-text">Price per night: $<%= @listing.price %></p>
        <p class="card-text">Type of room: <%= @listing.type_of_room %></p>
        <p class="card-text">Category: <%= @listing.category %></p>
        <hr> 
        <p class="card-text" style='font-weight: bold;'>Check-in date: <%= @reservation.check_in %></p>
        <p class="card-text" style='font-weight: bold;'>Check-out date: <%= @reservation.check_out %></p>  
        <p class="card-text" style='font-weight: bold;'>Total payable amount: $<%= @total_price %></p>  
    </div>

    <%= button_to "Pay now", reservation_braintree_new_path(@reservation.id) , method: :get, class: "btn btn-primary"%>
    <hr>
    <!--/.Card content-->
    <h10 class="hosted">Hosted By:<%= User.find(@listing.user_id).name  %></h10>
    <br>
    <% if @listing.verify == true %>
        <%= link_to "Verified by admin", verify_path(current_user.id), method: :post %> 
    <% else %>
        <%= link_to "Not verified by admin", verify_path(current_user.id), method: :post %> 
    <% end %> 
</div>
<br>