config/routes.rb
Rails.application.routes.draw do
  get 'listings/new'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create, :edit, :update] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
      # resources :listings
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "users#index"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "/profile" => "users#profile"

  resources :listings do 
    resources :reservations
  end 

  get "/search" => "listings#search"
  post "/listings/:id/verify" => "listings#verify", as: 'verify'

  resources :reservations, only: [:show] do 
    get "braintree/new" => "braintree#new"
    post "braintree/checkout" => "braintree#checkout"
  end 

  get "/reservations" => "reservations#all"
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark navbar-custom">
  <div class="container-fluid">
    <ul class="nav navbar-nav">
      <li class="active"><%= link_to "Home", root_path %></li>
      <% if signed_in? -%>
      <div class='searchbar'>
        <li> <%= render partial: 'layouts/searchbar' %> </li>
      </div>
      <div class='right'>
      <ul class="nav navbar-nav">
        <% if current_user.avatar.url == nil %>
          <li> <%= link_to image_tag("images.png", class: "sample_avatar"), profile_path%></li>
        <% else %>
          <li> <%= link_to image_tag("#{current_user.avatar.url}", class: "avatar"), profile_path%></li>
        <% end %>
      <li> <%= link_to t(".sign_out"), sign_out_path, method: :delete, class: "sign_out" %></li>
      <% else %>
      <li> <%= link_to "Sign in with Facebook", "/auth/facebook" %></li>
      <li> <%= link_to t(".sign_up"), sign_up_path %></li>
      </ul>
      </div>
      <% end -%>
    	<li><%= link_to "About Us", "#" %></li>
      </div>
    </ul>
  </div>
</nav> 

app/views/layouts/_searchbar.html.erb
<%= form_for :search, url: search_path, html: { class: "search_form"} , method: :get do |form| %>

	<div class='general-field'>
	<%= form.text_field :title, placeholder: "Search location here", name: 'search[general]' , class: "form-control"%>
	</div>

   <div class="room-field">
   	<%= form.select "type", options_for_select([["Select Room", ""],["Private Room", "Private Room"],["Entire Place", "Entire Place"],["Shared Room", "Shared Room"]]) , {}, {:class => "form-control"} %>
   </div>

	<div class="category-field">
	<%= form.select "category", options_for_select([["Select Category", ""], ["Smoker", "Smoker"], ["Non-Smoker", "Non-Smoker"], ["Pet", "Pet"]]) , {}, {:class => "form-control"}%>
	</div>
	
	<div class="form-group row">
	  <%= form.number_field :guest, class: "form-control" %>
	</div>

   <%= form.submit 'Search', :class => 'btn btn-primary'%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<%= render partial: "layouts/navbar" %>

  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div>

  <%= yield %>

</body>


</html>